services:
  service_name:
    build: .
    image: {{ cookiecutter.project_name }}:latest
    container_name: {{ cookiecutter.project_name }}
    restart: unless-stopped
    environment:
      - DATABASE_PATH=/app/main.db
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app